# Generated by Django 5.0.2 on 2024-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_worker_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='worker_lists', to='users.worker'),
        ),
    ]
