# Generated by Django 5.0.2 on 2024-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_workerlist_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
