# Generated by Django 5.0.2 on 2024-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_workerlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='workers',
            field=models.ManyToManyField(related_name='worker_lists', to='users.worker'),
        ),
    ]
