# Generated by Django 5.0.2 on 2024-02-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_workerlist_workers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerList',
        ),
    ]
