# Generated by Django 5.0.2 on 2024-02-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_klient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('couse_time', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=200)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specializations', models.ManyToManyField(related_name='staff_specializations', to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
    ]
