# Generated by Django 5.0.2 on 2024-03-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_record_staff_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service')),
            ],
        ),
    ]
