# Generated by Django 5.0.2 on 2024-03-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_recordnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='servicesList',
            field=models.ManyToManyField(related_name='workers', to='users.service'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='work_schedule',
            field=models.ManyToManyField(related_name='workers', to='users.workschedule'),
        ),
    ]
